Repository redBorder/cookbook-snort, pull requests merged in 2024-04, with the labels that each got.

#4 Modify geoip_db path
  resources/templates/default/snort-preprocessors-default.conf.erb
Labels: size/XS, kind/bug

#6 Release 0.1.1
  CHANGELOG.md
  resources/metadata.rb
Labels: size/XS, release, kind/documentation

#8 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: kind/feature, size/M
